//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication12
{
    using System;
    using System.Collections.Generic;
    
    public partial class DueTran
    {
        public int DueTranID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<float> DueAmount { get; set; }
        public string Remarks { get; set; }
    
        public virtual LibraryMember LibraryMember { get; set; }
    }
}
